### ISSUE TITLE
Display percentage of submitted shares

### ISSUE THREAD

**Issue by Sail86** [hellcatz/luckpool#15]
Display percentage of submitted shares by a miner to total submitted shares on pool.
e.g. on miner page next to shares amount "1234.567 (8.5%)"

**Comment by hellcatz** [comment]
I'll work on adding back "miner efficiency" as can be seen on the old site.
Unfortunately, I don't have a share count, but a share value based on the miner's present difficulty.

**Comment by Sail86** [comment]
we got total share count on `luckpool.net/zen/` and miner share count on `luckpool.net/zen/miner.html?xxx` so thats just some rule of three ? :-P

**Comment by Sail86** [comment]
Well this wont be applicable with with hybrid-PPLNS schemes.
At least not to achieve as easy ... guess this can be neglected.
