### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by hellcatz** [hellcatz/luckpool#25]
Work-In-Progress theme for when you want to hide in the dark.

**Comment by SolWax** [comment]
Confirmed on mobile using Chrome, Galaxy S9+.

**Comment by hellcatz** [comment]
Currently, you may click on your miner address on your miner page to "experiment" with Night Mode.
![image](https://user-images.githubusercontent.com/22487711/41185730-54773492-6b40-11e8-8ada-c87819006471.png)
In the future their will be an "Auto, Day, Night" selection and your preference will be saved in a cookie.

**Comment by SolWax** [comment]
Hard to see items: ZENCASH at top of page, payment blocks in center, worker name under jackpots tab (maybe bold here would be enough).

**Comment by hellcatz** [comment]
I'll leave this issue open for others to comment on the "coloring" of some elements between both Day/Night mode. Got to start somewhere 👍

**Comment by dudezmobi** [comment]
different font usage on night and day mode

**Comment by VhaTer** [comment]
as in gitter lobby change the switch day/night to icons
other stuff look similar  ( hashrate-diff ) .

**Comment by dfelton** [comment]
Does night mode keep your rigs cooler? ;)

**Comment by dudezmobi** [comment]
this issue is ok! lets close this

**Comment by Sail86** [comment]
@hellcatz
