### ISSUE TITLE
ZClassic Update

### ISSUE THREAD

**Issue by Skellers21** [hellcatz/luckpool#37]
Hi

This is just to let you know that the ZClassic Community are addressing the current vulnerability disclosed by Zcash recently - we've prepared a medium article which explains what we're doing and gives an approximate timescale. We hope we can rely on your support with this update and links for any questions and further discussion can be found in the article

Many Thanks

Skellers

The ZClassic Community

===================

link to article

https://medium.com/@skellers/zclassic-upgrade-notice-faad6998ed39

**Comment by Skellers21** [comment]
Hi

Please find the link to the latest info for the Zclassic Update to address the vulnerability disclosed recently by Zcash

https://medium.com/@skellers/zclassic-sapling-the-new-core-d0eae720d826

Any questions, just let me know

Many thanks

Skellers

on behalf of the Zclassic Community and Zclassic CE

**Comment by hellcatz** [comment]
Pool is ready for ZClassic Sapling activation.
