### ISSUE TITLE
Hash rate for 24 hrs 

### ISSUE THREAD

**Issue by rb116** [hellcatz/luckpool#38]
Hi , 
I would like to request an additional average 24 hrs hash rate for miner which is very important to monitor your miners.

**Comment by hellcatz** [comment]
Replace 2HR average stat line on hashrate chart with 24hr average?
or
Add a 24HR average stat line to the hashrate chart?

**Comment by rb116** [comment]
Adding below the 2hrs will be better bcos most pool will hv 1/3/6/24 hrs. Current /2 hrs/24 looks good enou for me. 


Sent from Yahoo Mail for iPhone


On Thursday, March 14, 2019, 4:46 AM, hellcatz <notifications@github.com> wrote:


Replace 2HR average stat line on hashrate chart with 24hr average?
or
Add a 24HR average stat line to the hashrate chart?

**Comment by hellcatz** [comment]
24HR average has been added to main chart 👍

**Comment by rb116** [comment]
Thank you. 
So the left navigator showing 24 hrs now instead 2 hrs?


Sent from Yahoo Mail for iPhone


On Friday, March 22, 2019, 10:23 AM, hellcatz <notifications@github.com> wrote:


Closed #38.

**Comment by hellcatz** [comment]
![image](https://user-images.githubusercontent.com/22487711/54870764-11ad0500-4d68-11e9-81ba-6a3e3507d266.png)
The yellow highlight is the 24 hour average.
You can also click on the labels in the chart legend to toggle the line on/off.

**Comment by rb116** [comment]
Yup. Noted. Looks good. 
Last but not least, do u mind to chg the colours for EU OR AP under stats bcos both color’s looks quite similar and difficult to differentiated. 
Tks


Sent from Yahoo Mail for iPhone


On Sunday, March 24, 2019, 3:35 AM, hellcatz <notifications@github.com> wrote:



The yellow highlight is the 24 hour average.
You can also click on the labels in the chart legend to toggle the line on/off.
