### ISSUE TITLE
Share rejection on Z9M increased

### ISSUE THREAD

**Issue by dudezmobi** [hellcatz/luckpool#39]
rb116
@rb116
01:12
how about rejection ?
i scared a shares was expired when submitted late
i noticed my mini lower hash now and more rejected shares
hellcatz
@hellcatz
01:18
What coin and stratum server do you mine on?
We can experiment with going back to 12 on that coin/stratum specifically.
However, the difficulty really shouldn't affect rejects, unless its way too low and miner is spamming shares...
I know this is not the case with Z9M at diff setting of 16...just an example...

**Comment by hellcatz** [comment]
This issue has been resolved.

**Comment by rb116** [comment]
Yup. Closed


Sent from Yahoo Mail for iPhone


On Sunday, June 2, 2019, 11:47 AM, hellcatz <notifications@github.com> wrote:


Closed #39.
