### ISSUE TITLE
Computation for AVG 1D

### ISSUE THREAD

**Issue by dudezmobi** [hellcatz/luckpool#4]
AVG 1D display and computation is not accurate when i stopped mining for 10 Days. 1D display keeps giving me the wrong value.

**Comment by hellcatz** [comment]
AVG 1D is based off last 3 days of payments. This may become inaccurate in the scenario mentioned as no further payments are sent and the prior payment data is being used for calculations.

**Comment by dudezmobi** [comment]
can you add some context message saying payments are still inaccurate? thanks

**Comment by dudezmobi** [comment]
added experimental label
