### ISSUE TITLE
Mac build? Happy to help test

### ISSUE THREAD

**Issue by VoskCoin** [hellcatz/luckpool#44]
With the new Mac Pro's having good spec's and being built around powerful CPUs, I'd love to see a mac build. I'd be happy to help test it for you. I've got a 3.2 GHz 16-Core Intel Xeon W on board.

**Comment by Dude-WTF** [comment]
holy VoskCoin... you're still alive? :) hellcatz doesnt have a macOS avail to build/compile to test....

**Comment by dfelton** [comment]
VoskCoin! Nice, watch your videos on the regular. Hope the new home is working out well for ya man.

lol off topic from issue immediately.
